[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
cmds = ["npm ci --prefer-offline", "pip install --no-cache-dir -r requirements.txt"]
cacheDirectories = ["node_modules", ".prisma"]

[start]
cmd = "npm start"
