import express from 'express';
import { postToInstagram, getRecentMedia } from '../services/instagramService.js';

const router = express.Router();

// router.use(requireAuth); // Protect in production if needed

/**
 * POST /api/instagram/post
 * Payload: { imageUrl, caption }
 */
router.post('/post', async (req, res) => {
    try {
        const { imageUrl, caption } = req.body;
        
        if (!imageUrl) {
            return res.status(400).json({ error: 'imageUrl is required' });
        }

    const result = await postToInstagram(imageUrl, caption || 'Generated by LiraOS 🤖✨');
        res.json(result);

    } catch (error) {
        console.error('[INSTAGRAM ROUTE ERROR]', error);
        res.status(500).json({ error: error.message });
    }
});

/**
 * POST /api/instagram/create-reel
 * Payload: { script, imageUrl, voice, caption, autoPost }
 */
import { createShortVideo } from '../services/videoCreatorService.js';
import { postToInstagramReel } from '../services/instagramService.js';

router.post('/create-reel', async (req, res) => {
    try {
        const { script, imageUrl, voice, caption, autoPost = false } = req.body;

        if (!script || !imageUrl) {
            return res.status(400).json({ error: 'Script and ImageURL are required' });
        }

        // 1. Create Video
        console.log('[API] Creating Reel Video...');
        const videoResult = await createShortVideo(script, imageUrl, voice);
        
        // Construct public URL
        const videoUrl = `${process.env.NGROK_URL || process.env.BACKEND_URL || 'http://localhost:4000'}${videoResult.url}`;
        
        // 2. Auto Post if requested (and if we have a public URL)
        let postResult = null;
        if (autoPost) {
            if (!videoUrl.includes('localhost') && !videoUrl.includes('127.0.0.1')) {
                postResult = await postToInstagramReel(videoUrl, caption || script.substring(0, 100));
            } else {
                console.warn('[API] Skipping Auto-Post: Video URL is localhost (IG needs public access)');
                postResult = { success: false, message: 'Skipped Auto-Post: URL is not public' };
            }
        }

        res.json({
            success: true,
            video: {
                filename: videoResult.filename,
                localUrl: videoResult.url,
                publicUrl: videoUrl
            },
            post: postResult
        });

    } catch (error) {
        console.error('[Create Reel Error]', error);
        res.status(500).json({ error: error.message });
    }
});

/**
 * GET /api/instagram/feed
 */
router.get('/feed', async (req, res) => {
    try {
        const posts = await getRecentMedia(10);
        res.json(posts);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

export default router;
