import express from 'express';
import { requireAuth } from '../middlewares/authMiddleware.js';
import { postToInstagram, getRecentMedia } from '../services/instagramService.js';

const router = express.Router();

// Public or Protected? Let's protect it. Only Lira/Owner should post.
// router.use(requireAuth);

/**
 * POST /api/social/instagram/post
 * Payload: { imageUrl, caption }
 */
router.post('/instagram/post', async (req, res) => {
    try {
        const { imageUrl, caption } = req.body;
        
        if (!imageUrl) {
            return res.status(400).json({ error: 'imageUrl is required' });
        }

        const result = await postToInstagram(imageUrl, caption || 'Generated by LiraOS 🤖✨');
        res.json(result);

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * GET /api/social/instagram/feed
 */
router.get('/instagram/feed', async (req, res) => {
    try {
        const posts = await getRecentMedia(10);
        res.json(posts);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

export default router;
